name: Test and Release

on:
  push:
    branches:
      - main  # Esegui l'azione sui push al branch "main"
  workflow_dispatch:  # Permette di avviare manualmente il workflow

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9  # Specifica la versione di Python (puoi aggiungere altre versioni)

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run tests
        run: python -m unittest discover -s tests

  build:
    name: Build Distribution Files
    needs: test  # Esegui solo se il job "test" ha successo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build distribution files
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build  # Esegui solo se la build è completata
    if: github.event_name == 'workflow_dispatch'  # Trigger manuale richiesto

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
